---
title: "SPP for C"
output: html_notebook
---

```{r}
library(forecast)
library(ggplot2)
library(readr)
```

```{r}
C <- read_csv("~/R/SPP/CSV/C.csv", col_types = cols(Week = col_date(format = "%Y-%m-%d")))
c <- ts(C[,2], freq=365.25/7, start=2017+223.50/365.25)
c %>%
  autoplot()
```

```{r}
plot(decompose(c))
```

```{r}
training_c <- subset(c, end=length(c)-1)
test_c <- subset(c, start=length(c)-1)
fc_training_c<-forecast(training_c)
fc_training_c %>%
  forecast(h=26) %>%
  autoplot() +autolayer(test_c)
```

```{r}
fc_training_c
```

```{r}
fc_c<-forecast(c)
fc_c %>%
  forecast(h=40) %>%
  autoplot()
```

```{r}
fc_c
```

```{r}
tail(c)
min(c)
max(c)
which.min(c)
```

```{r}
bestfit_c <- list(aicc=Inf)
for(i in 1:25)
{
  fit_c <- auto.arima(c, xreg=fourier(c, K=i), seasonal=FALSE)
  if(fit_c$aicc < bestfit_c$aicc)
    bestfit_c <- fit_c
  else break;
}
```

```{r}
summary(bestfit_c)
```

```{r}
fc_arima_c <- forecast(bestfit_c, xreg=fourier(c, K=3, h=26))
plot(fc_arima_c)
```

```{r}
fc_arima_c
```

```{r}
fit_c1 <- auto.arima(c, xreg=fourier(c, K=1), seasonal=FALSE)
fit_c2 <- auto.arima(c, xreg=fourier(c, K=2), seasonal=FALSE)
fit_c3 <- auto.arima(c, xreg=fourier(c, K=3), seasonal=FALSE)
fit_c4 <- auto.arima(c, xreg=fourier(c, K=4), seasonal=FALSE)
fit_c5 <- auto.arima(c, xreg=fourier(c, K=5), seasonal=FALSE)
fit_c6 <- auto.arima(c, xreg=fourier(c, K=6), seasonal=FALSE)
fit_c7 <- auto.arima(c, xreg=fourier(c, K=7), seasonal=FALSE)
fit_c8 <- auto.arima(c, xreg=fourier(c, K=8), seasonal=FALSE)
fit_c9 <- auto.arima(c, xreg=fourier(c, K=9), seasonal=FALSE)
fit_c10 <- auto.arima(c, xreg=fourier(c, K=10), seasonal=FALSE)
fit_c11 <- auto.arima(c, xreg=fourier(c, K=11), seasonal=FALSE)
fit_c12 <- auto.arima(c, xreg=fourier(c, K=12), seasonal=FALSE)
```

```{r}
aics<-c(AIC(fit_c1),AIC(fit_c2),AIC(fit_c3),AIC(fit_c4),AIC(fit_c5),AIC(fit_c6),AIC(fit_c7),AIC(fit_c8),AIC(fit_c9),AIC(fit_c10),AIC(fit_c11),AIC(fit_c12))
plot(aics)
```

```{r}
fc_c5 <- forecast(fit_c5, xreg=fourier(c, K=5, h=26))
plot(fc_c5)
```

```{r}
fc_c5
```

```{r}
accuracy(fc_c)
```

```{r}
accuracy(fc_arima_c)
```

```{r}
accuracy(fc_c5)
```