---
title: "SPP for FNI"
output: html_notebook
---

```{r}
library(forecast)
library(ggplot2)
library(readr)
```

```{r}
FNI <- read_csv("~/R/SPP/CSV/FNI.csv", col_types = cols(Week = col_date(format = "%Y-%m-%d")))
fni <- ts(FNI[,2], freq=365.25/7, start=2015+191/365.25)
fni %>%
  autoplot()
```

```{r}
plot(decompose(fni))
```

```{r}
training_fni <- subset(fni, end=length(fni)-1)
test_fni <- subset(fni, start=length(fni)-1)
fc_training_fni<-forecast(training_fni)
fc_training_fni %>%
  forecast(h=26) %>%
  autoplot() +autolayer(test_fni)
```

```{r}
fc_training_fni
```

```{r}
fc_fni<-forecast(fni)
fc_fni %>%
  forecast(h=26) %>%
  autoplot()
```

```{r}
fc_fni
```

```{r}
tail(fni)
min(fni)
max(fni)
which.min(fni)
```

```{r}
bestfit_fni <- list(aicc=Inf)
for(i in 1:25)
{
  fit_fni <- auto.arima(fni, xreg=fourier(fni, K=i), seasonal=FALSE)
  if(fit_fni$aicc < bestfit_fni$aicc)
    bestfit_fni <- fit_fni
  else break;
}
```

```{r}
summary(bestfit_fni)
```

```{r}
fc_arima_fni <- forecast(bestfit_fni, xreg=fourier(fni, K=1, h=26))
plot(fc_arima_fni)
```

```{r}
fc_arima_fni
```

```{r}
fit_fni1 <- auto.arima(fni, xreg=fourier(fni, K=1), seasonal=FALSE)
fit_fni2 <- auto.arima(fni, xreg=fourier(fni, K=2), seasonal=FALSE)
fit_fni3 <- auto.arima(fni, xreg=fourier(fni, K=3), seasonal=FALSE)
fit_fni4 <- auto.arima(fni, xreg=fourier(fni, K=4), seasonal=FALSE)
fit_fni5 <- auto.arima(fni, xreg=fourier(fni, K=5), seasonal=FALSE)
fit_fni6 <- auto.arima(fni, xreg=fourier(fni, K=6), seasonal=FALSE)
fit_fni7 <- auto.arima(fni, xreg=fourier(fni, K=7), seasonal=FALSE)
fit_fni8 <- auto.arima(fni, xreg=fourier(fni, K=8), seasonal=FALSE)
fit_fni9 <- auto.arima(fni, xreg=fourier(fni, K=9), seasonal=FALSE)
fit_fni10 <- auto.arima(fni, xreg=fourier(fni, K=10), seasonal=FALSE)
fit_fni11 <- auto.arima(fni, xreg=fourier(fni, K=11), seasonal=FALSE)
fit_fni12 <- auto.arima(fni, xreg=fourier(fni, K=12), seasonal=FALSE)
```

```{r}
aics<-c(AIC(fit_fni1),AIC(fit_fni2),AIC(fit_fni3),AIC(fit_fni4),AIC(fit_fni5),AIC(fit_fni6),AIC(fit_fni7),AIC(fit_fni8),AIC(fit_fni9),AIC(fit_fni10),AIC(fit_fni11),AIC(fit_fni12))
plot(aics)
```

```{r}
fc_fni2 <- forecast(fit_fni2, xreg=fourier(fni, K=2, h=26))
plot(fc_fni2)
```

```{r}
fc_fni2
```

```{r}
accuracy(fc_fni)
```

```{r}
accuracy(fc_arima_fni)
```

```{r}
accuracy(fc_fni2)
```