---
title: "SPP for SMC"
output: html_notebook
---

```{r}
library(forecast)
library(ggplot2)
library(readr)
```

```{r}
SMC <- read_csv("~/R/SPP/CSV/SMC.csv", col_types = cols(Week = col_date(format = "%Y-%m-%d")))
smc <- ts(SMC[,2], freq=365.25/7, start=2015+44/365.25)
smc %>%
  autoplot()
```

```{r}
plot(decompose(smc))
```

```{r}
training_smc <- subset(smc, end=length(smc)-1)
test_smc <- subset(smc, start=length(smc)-1)
fc_training_smc<-forecast(training_smc)
fc_training_smc %>%
  forecast(h=26) %>%
  autoplot() +autolayer(test_smc)
```

```{r}
fc_training_smc
```

```{r}
fc_smc<-forecast(smc)
fc_smc %>%
forecast(h=26) %>%
  autoplot()
```

```{r}
fc_smc
```

```{r}
tail(smc)
min(smc)
max(smc)
which.min(smc)
```

```{r}
bestfit_smc <- list(aicc=Inf)
for(i in 1:25)
{
  fit_smc <- auto.arima(smc, xreg=fourier(smc, K=i), seasonal=FALSE)
  if(fit_smc$aicc < bestfit_smc$aicc)
    bestfit_smc <- fit_smc
  else break;
}
```

```{r}
summary(bestfit_smc)
```

```{r}
fc_arima_smc <- forecast(bestfit_smc, xreg=fourier(smc, K=1, h=26))
plot(fc_arima_smc)
```

```{r}
fc_arima_smc
```

```{r}
fit_smc1 <- auto.arima(smc, xreg=fourier(smc, K=1), seasonal=FALSE)
fit_smc2 <- auto.arima(smc, xreg=fourier(smc, K=2), seasonal=FALSE)
fit_smc3 <- auto.arima(smc, xreg=fourier(smc, K=3), seasonal=FALSE)
fit_smc4 <- auto.arima(smc, xreg=fourier(smc, K=4), seasonal=FALSE)
fit_smc5 <- auto.arima(smc, xreg=fourier(smc, K=5), seasonal=FALSE)
fit_smc6 <- auto.arima(smc, xreg=fourier(smc, K=6), seasonal=FALSE)
fit_smc7 <- auto.arima(smc, xreg=fourier(smc, K=7), seasonal=FALSE)
fit_smc8 <- auto.arima(smc, xreg=fourier(smc, K=8), seasonal=FALSE)
fit_smc9 <- auto.arima(smc, xreg=fourier(smc, K=9), seasonal=FALSE)
fit_smc10 <- auto.arima(smc, xreg=fourier(smc, K=10), seasonal=FALSE)
fit_smc11 <- auto.arima(smc, xreg=fourier(smc, K=11), seasonal=FALSE)
fit_smc12 <- auto.arima(smc, xreg=fourier(smc, K=12), seasonal=FALSE)
```

```{r}
aics<-c(AIC(fit_smc1),AIC(fit_smc2),AIC(fit_smc3),AIC(fit_smc4),AIC(fit_smc5),AIC(fit_smc6),AIC(fit_smc7),AIC(fit_smc8),AIC(fit_smc9),AIC(fit_smc10),AIC(fit_smc11),AIC(fit_smc12))
plot(aics)
```

```{r}
fc_smc2 <- forecast(fit_smc2, xreg=fourier(smc, K=2, h=26))
plot(fc_smc2)
```

```{r}
fc_smc2
```

```{r}
accuracy(fc_smc)
```

```{r}
accuracy(fc_arima_smc)
```

```{r}
accuracy(fc_smc2)
```