---
title: "SPP"
author: NVSUBSEDMATH
output: html_notebook
---
We are going to get data from 

```{r}
load("~/R/SPP/SPP.RData")
```

# ALLHC

```{r}
allhc <- ts(ALLHC[,2], freq=365.25/7, start=2015+37/365.25)
plot(allhc)
acf(allhc)
```

```{r}
plot(decompose(allhc))
```


```{r}
library(forecast)
bestfit_allhc <- list(aicc=Inf)
for(i in 1:25)
{
  fit_allhc <- auto.arima(allhc, xreg=fourier(allhc, K=i), seasonal=FALSE)
  if(fit_allhc$aicc < bestfit_allhc$aicc)
    bestfit_allhc <- fit_allhc
  else break;
}
```


```{r}
summary(bestfit_allhc)
```


```{r}
fc_allhc <- forecast(bestfit_allhc, xreg=fourier(allhc, K=1, h=200))
plot(fc_allhc)
```


```{r}
summary(fc_allhc)
```

# FSHA ALLHC

```{r}
Allhc<-allhc[1:262]
P = abs(fft(Allhc)); Fr = 0:261
plot(Fr, P, type="o", xlab="frequency", ylab="periodogram",ylim=c(0,700))
```

```{r}
f<-abs(fft(Allhc))
a<-which(f>20)
b<-(a-1)*2
b
```

```{r}
t<-1:262
x=y=matrix(nr=length(t),nc=25)
x[,1]<-cos(2*pi*t/262)
y[,1]<-sin(2*pi*t/262)
x[,2]<-cos(4*pi*t/262)
y[,2]<-sin(4*pi*t/262)
x[,3]<-cos(6*pi*t/262)
y[,3]<-sin(6*pi*t/262)
x[,4]<-cos(8*pi*t/262)
y[,4]<-sin(8*pi*t/262)
x[,5]<-cos(12*pi*t/262)
y[,5]<-sin(12*pi*t/262)
```

```{r}
mmm<-lm(Allhc~x[,4]+y[,4])
plot(Allhc,type="l")
lines(1:262,mmm$fitted.values,col="red")
```

```{r}
summary(mmm)
```


```{r}
allhcdummy<-allhc[150:262]
allhcdummy<-c(allhcdummy,2*allhcdummy,3*allhcdummy,3.5*allhcdummy,4*allhcdummy,4.2*allhcdummy)
```

```{r}
allhcdummy <- ts(allhcdummy, freq=365.25/7, start=2015+342/365.25)
plot(allhcdummy)
```

```{r}
library(forecast)
bestfit_allhcd <- list(aicc=Inf)
for(i in 1:25)
{
  fit_allhcd <- auto.arima(allhcdummy, xreg=fourier(allhcdummy, K=i), seasonal=FALSE)
  if(fit_allhcd$aicc < bestfit_allhcd$aicc)
    bestfit_allhcd <- fit_allhcd
  else break;
}
```

```{r}
summary(bestfit_allhcd)
```

```{r}
fc_allhcd <- forecast(bestfit_allhcd, xreg=fourier(allhcdummy, K=1, h=200))
plot(fc_allhcd)
```

```{r}
plot(decompose(allhcdummy))
```


```{r}
fit_allhcd24 <- auto.arima(allhcdummy, xreg=fourier(allhcdummy, K=24), seasonal=FALSE)
```

```{r}
fc_allhcd24 <- forecast(fit_allhcd24, xreg=fourier(allhcdummy, K=24, h=200))
plot(fc_allhcd24)
```

```{r}
plot(forecast(allhcdummy))
```


# FOOD

```{r}
food <- ts(FOOD[,2], freq=(365.25/7), start=2015+44/365.25)
plot(food)
acf(food)
```

```{r}
plot(decompose(food))
```

```{r}
bestfit_food <- list(aicc=Inf)
for(i in 1:25)
{
  fit_food <- auto.arima(food, xreg=fourier(food, K=i), seasonal=FALSE)
  if(fit_food$aicc < bestfit_food$aicc)
    bestfit_food <- fit_food
  else break;
}
```

```{r}
summary(bestfit_food)
```

```{r}
fc_food <- forecast(bestfit_food, xreg=fourier(food, K=1, h=105))
plot(fc_food)
```

```{r}
summary(fc_food)
```

```{r}
plot(forecast(food))
```


# SMC

```{r}
smc <- ts(SMC[,2], freq=(365.25/7), start=2015+44/365.25)
plot(smc)
acf(smc)
```

```{r}
plot(decompose(smc))
```

```{r}
bestfit_smc <- list(aicc=Inf)
for(i in 1:25)
{
  fit_smc <- auto.arima(smc, xreg=fourier(smc, K=i), seasonal=FALSE)
  if(fit_smc$aicc < bestfit_smc$aicc)
    bestfit_smc <- fit_smc
  else break;
}
```

```{r}
summary(bestfit_smc)
```

```{r}
fc_smc <- forecast(bestfit_smc, xreg=fourier(smc, K=1, h=200))
plot(fc_smc)
```

```{r}
summary(fc_smc)
```

```{r}
fit_smc2 <- auto.arima(smc, xreg=fourier(smc, K=2), seasonal=FALSE)
```

```{r}
fc_smc2 <- forecast(fit_smc2, xreg=fourier(smc, K=2, h=200))
plot(fc_smc2)
```

```{r}
AIC(fit_smc5)
```

```{r}
plot(c(AIC(fit_smc),AIC(fit_smc2),AIC(fit_smc3),AIC(fit_smc4),AIC(fit_smc5),AIC(fit_smc6),AIC(fit_smc7),AIC(fit_smc8)))
```

```{r}
plot(forecast(smc))
```

```{r}
forecast(smc)
```

```{r}
smc_train<-window(smc,end=2018.999)
plot(smc_train)
```

```{r}
smc_test<-window(smc,start=2019)
plot(smc_test)
```

```{r}
fc_smc_train<-forecast(smc_train,h=58)
```

```{r}
accuracy(fc_smc_train,smc_test)
```

```{r}
plot.ts(smc_test)
```

```{r}
plot(fc_smc_train_mean)
```



