---
title: "Stock Price Forecasting"
author: "Blessing R. Ildefonso"
format: html
editor: visual
---

# Background

```{r}
library(forecast) #loads the forecast package
library(ggplot2) #loads the ggplot2 package
library(readr) #loads the readr package
library(zoo) #loads the zoo package

```

```{r}
TUGO <- read_csv("/cloud/project/CSV/2GO.csv", col_types = cols(Week = col_date(format = "%Y-%m-%d")))
tugo <- ts(TUGO[,2], freq=365.25/7, start=2015+128/365.25)
tugo %>%
  autoplot()
```

```{r}
tugo_decomp <- decompose(na.locf(tugo), type="additive")
autoplot (tugo_decomp)
```

```{r}
training_tugo <- subset(tugo,end=length(tugo)-8)
test_tugo <- subset(tugo,start=length(tugo)-8)
fc_training_tugo<-forecast(training_tugo)
fc_training_tugo%>%
  forecast(h=60)%>%
  autoplot() +autolayer(test_tugo)
```

```{r}
fc_training_tugo
```

```{r}
fc_tugo<-forecast(tugo)
fc_tugo %>%
  forecast(h=27) %>%
  autoplot()
```

```{r}
fc_tugo
```

```{r}
tail(tugo)
min(tugo)
max(tugo)
which.min(tugo)
```

```{r}
bestfit_tugo <- list(aicc=Inf)
for(i in 1:25)
{
  fit_tugo <- auto.arima(tugo, xreg=fourier(tugo, K=i), seasonal=FALSE)
  if(fit_tugo$aicc < bestfit_tugo$aicc)
    bestfit_tugo <- fit_tugo
  else break;
}
```

```{r}
summary(bestfit_tugo)
```

```{r}
fc_arima_tugo <- forecast(bestfit_tugo, xreg=fourier(tugo, K=1, h=26))
plot(fc_arima_tugo)
```

```{r}
fc_arima_tugo
```

```{r}
fit_tugo1 <- auto.arima(tugo, xreg=fourier(tugo, K=1), seasonal=FALSE)
fit_tugo2 <- auto.arima(tugo, xreg=fourier(tugo, K=2), seasonal=FALSE)
fit_tugo3 <- auto.arima(tugo, xreg=fourier(tugo, K=3), seasonal=FALSE)
fit_tugo4 <- auto.arima(tugo, xreg=fourier(tugo, K=4), seasonal=FALSE)
fit_tugo5 <- auto.arima(tugo, xreg=fourier(tugo, K=5), seasonal=FALSE)
fit_tugo6 <- auto.arima(tugo, xreg=fourier(tugo, K=6), seasonal=FALSE)
fit_tugo7 <- auto.arima(tugo, xreg=fourier(tugo, K=7), seasonal=FALSE)
fit_tugo8 <- auto.arima(tugo, xreg=fourier(tugo, K=8), seasonal=FALSE)
fit_tugo9 <- auto.arima(tugo, xreg=fourier(tugo, K=9), seasonal=FALSE)
fit_tugo10 <- auto.arima(tugo, xreg=fourier(tugo, K=10), seasonal=FALSE)
fit_tugo11 <- auto.arima(tugo, xreg=fourier(tugo, K=11), seasonal=FALSE)
fit_tugo12 <- auto.arima(tugo, xreg=fourier(tugo, K=12), seasonal=FALSE)
```

```{r}
aics<-c(AIC(fit_tugo1),AIC(fit_tugo2),AIC(fit_tugo3),AIC(fit_tugo4),AIC(fit_tugo5),AIC(fit_tugo6),AIC(fit_tugo7),AIC(fit_tugo8),AIC(fit_tugo9),AIC(fit_tugo10),AIC(fit_tugo11),AIC(fit_tugo12))
plot(aics)
```

```{r}
fc_tugo1 <- forecast(fit_tugo1, xreg=fourier(tugo, K=1, h=26))
plot(fc_tugo1)
```

```{r}
fc_tugo1
```

```{r}
accuracy(fc_tugo)
```

```{r}
accuracy(fc_arima_tugo)
```

```{r}
ACEN <- read_csv("/cloud/project/CSV/ACEN.csv", col_types = cols(Week = col_date(format = "%Y-%m-%d")))
acen <- ts(ACEN[,2], freq=365.25/7, start=2015+65/365.25)
acen%>%
  autoplot()
```

```{r}
acen_decomp <- decompose(na.locf(acen), type="additive")
autoplot (acen_decomp)
```

```{r}
training_acen <- subset(acen, end=length(acen)-1)
test_acen <- subset(acen, start=length(acen)-1)
fc_training_acen<-forecast(training_acen)
fc_training_acen %>%
  forecast(h=26) %>%
  autoplot() +autolayer(test_acen)
```

```{r}
fc_training_acen
```

```{r}
fc_acen<-forecast(acen)
fc_acen %>%
  forecast(h=26) %>%
  autoplot()
```

```{r}
fc_acen
```

```{r}
tail(acen)
min(acen)
max(acen)
which.min(acen)
```

```{r}
bestfit_acen <- list(aicc=Inf)
for(i in 1:25)
{
  fit_acen <- auto.arima(acen, xreg=fourier(acen, K=i), seasonal=FALSE)
  if(fit_acen$aicc < bestfit_acen$aicc)
    bestfit_acen <- fit_acen
  else break;
}
```

```{r}
summary(bestfit_acen)
```

```{r}
fc_arima_acen <- forecast(bestfit_acen, xreg=fourier(acen, K=1, h=52))
plot(fc_arima_acen)
```

```{r}
fc_arima_acen
```

```{r}
fit_acen1 <- auto.arima(acen, xreg=fourier(acen, K=1), seasonal=FALSE)
fit_acen2 <- auto.arima(acen, xreg=fourier(acen, K=2), seasonal=FALSE)
fit_acen3 <- auto.arima(acen, xreg=fourier(acen, K=3), seasonal=FALSE)
fit_acen4 <- auto.arima(acen, xreg=fourier(acen, K=4), seasonal=FALSE)
fit_acen5 <- auto.arima(acen, xreg=fourier(acen, K=5), seasonal=FALSE)
fit_acen6 <- auto.arima(acen, xreg=fourier(acen, K=6), seasonal=FALSE)
fit_acen7 <- auto.arima(acen, xreg=fourier(acen, K=7), seasonal=FALSE)
fit_acen8 <- auto.arima(acen, xreg=fourier(acen, K=8), seasonal=FALSE)
fit_acen9 <- auto.arima(acen, xreg=fourier(acen, K=9), seasonal=FALSE)
fit_acen10 <- auto.arima(acen, xreg=fourier(acen, K=10), seasonal=FALSE)
fit_acen11 <- auto.arima(acen, xreg=fourier(acen, K=11), seasonal=FALSE)
fit_acen12 <- auto.arima(acen, xreg=fourier(acen, K=12), seasonal=FALSE)
```

```{r}
aics<-c(AIC(fit_acen1),AIC(fit_acen2),AIC(fit_acen3),AIC(fit_acen4),AIC(fit_acen5),AIC(fit_acen6),AIC(fit_acen7),AIC(fit_acen8),AIC(fit_acen9),AIC(fit_acen10),AIC(fit_acen11),AIC(fit_acen12))
plot(aics)
```

```{r}
fc_acen2 <- forecast(fit_acen2, xreg=fourier(acen, K=2, h=26))
plot(fc_acen2)
```

```{r}
fc_acen2
```

```{r}
accuracy(fc_acen)
```

```{r}
accuracy(fc_arima_acen)
```
