---
title: "stock price forecasting"
author: "rizza pudao"
format: html
editor: visual
---

```{r}
library(forecast)
library(ggplot2)
library(readr)
library(zoo)
```

# Background

#### Graph for Megawide Construction Corp Price (MWIDE)

```{r}
MWIDE <- read_csv("/cloud/project/CSV/MWIDE.csv", col_types = cols(Week = col_date(format = "%Y-%m-%d")))
MWIDE_ts <- ts(MWIDE[,2], freq=365.25/7, start=2015+177/365.25)
MWIDE_ts %>%
  autoplot()
```

```{r}
td_decomp <- decompose(na.locf(MWIDE_ts), type="additive")
autoplot(td_decomp)
```

```{r}
training_MWIDE <- subset(MWIDE_ts, end=length(MWIDE_ts)-8)
test_MWIDE <- subset(MWIDE_ts, start=length(MWIDE_ts)-8)
fc_training_MWIDE<-forecast(training_MWIDE)
fc_training_MWIDE %>%
  forecast(h=10) %>%
  autoplot() +autolayer(test_MWIDE)
```

```{r}
fc_training_MWIDE
```

```{r}
fc_MWIDE<-forecast(MWIDE_ts)
fc_MWIDE %>%
  forecast(h=50) %>%
  autoplot()
```

```{r}
tail(MWIDE_ts)
min(MWIDE_ts)
max(MWIDE_ts)
which.min(MWIDE_ts)
```

```{r}
bestfit_MWIDE_ts <- list(aicc=Inf)
for(i in 1:25)
{
  fit_MWIDE_ts <- auto.arima(MWIDE_ts, xreg=fourier(MWIDE_ts, K=i), seasonal=FALSE)
  if(fit_MWIDE_ts$aicc < bestfit_MWIDE_ts$aicc)
    bestfit_MWIDE_ts <- fit_MWIDE_ts
  else break;
}
```

```{r}
summary(bestfit_MWIDE_ts)
```

```{r}
fc_arima_MWIDE_ts <- forecast(bestfit_MWIDE_ts, xreg=fourier(MWIDE_ts, K=1, h=26))
plot(fc_arima_MWIDE_ts)
```

```{r}
fc_arima_MWIDE_ts
```

```{r}
fit_MWIDE_ts1 <- auto.arima(MWIDE_ts, xreg=fourier(MWIDE_ts, K=1), seasonal=FALSE)
fit_MWIDE_ts2 <- auto.arima(MWIDE_ts, xreg=fourier(MWIDE_ts, K=2), seasonal=FALSE)
fit_MWIDE_ts3 <- auto.arima(MWIDE_ts, xreg=fourier(MWIDE_ts, K=3), seasonal=FALSE)
fit_MWIDE_ts4 <- auto.arima(MWIDE_ts, xreg=fourier(MWIDE_ts, K=4), seasonal=FALSE)
fit_MWIDE_ts5 <- auto.arima(MWIDE_ts, xreg=fourier(MWIDE_ts, K=5), seasonal=FALSE)
fit_MWIDE_ts6 <- auto.arima(MWIDE_ts, xreg=fourier(MWIDE_ts, K=6), seasonal=FALSE)
fit_MWIDE_ts7 <- auto.arima(MWIDE_ts, xreg=fourier(MWIDE_ts, K=7), seasonal=FALSE)
fit_MWIDE_ts8 <- auto.arima(MWIDE_ts, xreg=fourier(MWIDE_ts, K=8), seasonal=FALSE)
fit_MWIDE_ts9 <- auto.arima(MWIDE_ts, xreg=fourier(MWIDE_ts, K=9), seasonal=FALSE)
fit_MWIDE_ts10 <- auto.arima(MWIDE_ts, xreg=fourier(MWIDE_ts, K=10), seasonal=FALSE)
fit_MWIDE_ts11 <- auto.arima(MWIDE_ts, xreg=fourier(MWIDE_ts, K=11), seasonal=FALSE)
fit_MWIDE_ts12 <- auto.arima(MWIDE_ts, xreg=fourier(MWIDE_ts, K=12), seasonal=FALSE)
```

```{r}
aics<-c(AIC(fit_MWIDE_ts1),AIC(fit_MWIDE_ts2),AIC(fit_MWIDE_ts3),AIC(fit_MWIDE_ts4),AIC(fit_MWIDE_ts5),AIC(fit_MWIDE_ts6),AIC(fit_MWIDE_ts7),AIC(fit_MWIDE_ts8),AIC(fit_MWIDE_ts9),AIC(fit_MWIDE_ts10),AIC(fit_MWIDE_ts11),AIC(fit_MWIDE_ts12))
plot(aics)
```

```{r}
fc_MWIDE_ts1 <- forecast(fit_MWIDE_ts1, xreg=fourier(MWIDE_ts, K=1, h=26))
plot(fc_MWIDE_ts1)
```

```{r}
fc_MWIDE_ts1
```

```{r}
accuracy(fc_MWIDE_ts1)
```

```{r}
accuracy(fc_arima_MWIDE_ts)
```

```{r}
accuracy(fc_MWIDE_ts1)
```

#### Graph for NIKL

```{r}
NIKL <- read_csv("/cloud/project/CSV/NIKL.csv", col_types = cols(Week = col_date(format = "%Y-%m-%d")))
NIKL_ts <- ts(NIKL[,2], freq=365.25/7, start=2015+159/365.25)
NIKL_ts %>%
  autoplot()
```

```{r}
td_decomp <- decompose(na.locf(NIKL_ts), type="additive")
autoplot(td_decomp)
```

```{r}
training_NIKL <- subset(NIKL_ts, end=length(NIKL_ts)-8)
test_NIKL <- subset(NIKL_ts, start=length(NIKL_ts)-8)
fc_training_NIKL<-forecast(training_NIKL)
fc_training_NIKL %>%
  forecast(h=10) %>%
  autoplot() +autolayer(test_NIKL)
```

```{r}
fc_training_NIKL
```

```{r}
fc_NIKL<-forecast(NIKL_ts)
fc_NIKL %>%
  forecast(h=50) %>%
  autoplot()
```

```{r}
tail(NIKL_ts)
min(NIKL_ts)
max(NIKL_ts)
which.min(NIKL_ts)
```

```{r}
bestfit_NIKL_ts <- list(aicc=Inf)
for(i in 1:25)
{
  fit_NIKL_ts <- auto.arima(NIKL_ts, xreg=fourier(NIKL_ts, K=i), seasonal=FALSE)
  if(fit_NIKL_ts$aicc < bestfit_NIKL_ts$aicc)
    bestfit_NIKL_ts <- fit_NIKL_ts
  else break;
}
```

```{r}
summary(bestfit_NIKL_ts)
```

```{r}
fc_arima_NIKL_ts <- forecast(bestfit_NIKL_ts, xreg=fourier(NIKL_ts, K=1, h=26))
plot(fc_arima_NIKL_ts)
```

```{r}
fc_arima_NIKL_ts
```

```{r}
fit_NIKL_ts1 <- auto.arima(NIKL_ts, xreg=fourier(NIKL_ts, K=1), seasonal=FALSE)
fit_NIKL_ts2 <- auto.arima(NIKL_ts, xreg=fourier(NIKL_ts, K=2), seasonal=FALSE)
fit_NIKL_ts3 <- auto.arima(NIKL_ts, xreg=fourier(NIKL_ts, K=3), seasonal=FALSE)
fit_NIKL_ts4 <- auto.arima(NIKL_ts, xreg=fourier(NIKL_ts, K=4), seasonal=FALSE)
fit_NIKL_ts5 <- auto.arima(NIKL_ts, xreg=fourier(NIKL_ts, K=5), seasonal=FALSE)
fit_NIKL_ts6 <- auto.arima(NIKL_ts, xreg=fourier(NIKL_ts, K=6), seasonal=FALSE)
fit_NIKL_ts7 <- auto.arima(NIKL_ts, xreg=fourier(NIKL_ts, K=7), seasonal=FALSE)
fit_NIKL_ts8 <- auto.arima(NIKL_ts, xreg=fourier(NIKL_ts, K=8), seasonal=FALSE)
fit_NIKL_ts9 <- auto.arima(NIKL_ts, xreg=fourier(NIKL_ts, K=9), seasonal=FALSE)
fit_NIKL_ts10 <- auto.arima(NIKL_ts, xreg=fourier(NIKL_ts, K=10), seasonal=FALSE)
fit_NIKL_ts11 <- auto.arima(NIKL_ts, xreg=fourier(NIKL_ts, K=11), seasonal=FALSE)
fit_NIKL_ts12 <- auto.arima(NIKL_ts, xreg=fourier(NIKL_ts, K=12), seasonal=FALSE)
```

```{r}
aics<-c(AIC(fit_NIKL_ts1),AIC(fit_NIKL_ts2),AIC(fit_NIKL_ts3),AIC(fit_NIKL_ts4),AIC(fit_NIKL_ts5),AIC(fit_NIKL_ts6),AIC(fit_NIKL_ts7),AIC(fit_NIKL_ts8),AIC(fit_NIKL_ts9),AIC(fit_NIKL_ts10),AIC(fit_NIKL_ts11),AIC(fit_NIKL_ts12))
plot(aics)
```

```{r}
fc_NIKL_ts1 <- forecast(fit_NIKL_ts1, xreg=fourier(NIKL_ts, K=1, h=26))
plot(fc_NIKL_ts1)
```

```{r}
fc_NIKL_ts1
```

```{r}
accuracy(fc_NIKL_ts1)
```

```{r}
accuracy(fc_arima_NIKL_ts)
```

```{r}
accuracy(fc_NIKL_ts1)
```

#### Graph for NOW

```{r}
NOW <- read_csv("/cloud/project/CSV/NOW.csv", col_types = cols(Week = col_date(format = "%Y-%m-%d")))
NOW_ts <- ts(NOW[,2], freq=365.25/7, start=2015+158/365.25)
NOW_ts %>%
  autoplot()
```

```{r}
td_decomp <- decompose(na.locf(NOW_ts), type="additive")
autoplot(td_decomp)
```

```{r}
training_NOW  <- subset(NOW_ts, end=length(NOW_ts)-8)
test_NOW  <- subset(NOW_ts, start=length(NOW_ts)-8)
fc_training_NOW <-forecast(training_NOW )
fc_training_NOW  %>%
  forecast(h=10) %>%
  autoplot() +autolayer(test_NOW )
```

```{r}
fc_training_NOW 
```

```{r}
fc_NOW <-forecast(NOW_ts)
fc_NOW  %>%
  forecast(h=50) %>%
  autoplot()
```

```{r}
tail(NOW_ts)
min(NOW_ts)
max(NOW_ts)
which.min(NOW_ts)
```

```{r}
bestfit_NOW_ts <- list(aicc=Inf)
for(i in 1:25)
{
  fit_NOW_ts <- auto.arima(NOW_ts, xreg=fourier(NOW_ts, K=i), seasonal=FALSE)
  if(fit_NOW_ts$aicc < bestfit_NOW_ts$aicc)
    bestfit_NOW_ts <- fit_NOW_ts
  else break;
}
```

```{r}
summary(bestfit_NOW_ts)
```

```{r}
fc_arima_NOW_ts <- forecast(bestfit_NOW_ts, xreg=fourier(NOW_ts, K=1, h=26))
plot(fc_arima_NOW_ts)
```

```{r}
fc_arima_NOW_ts
```

```{r}
fit_NOW_ts1 <- auto.arima(NOW_ts, xreg=fourier(NOW_ts, K=1), seasonal=FALSE)
fit_NOW_ts2 <- auto.arima(NOW_ts, xreg=fourier(NOW_ts, K=2), seasonal=FALSE)
fit_NOW_ts3 <- auto.arima(NOW_ts, xreg=fourier(NOW_ts, K=3), seasonal=FALSE)
fit_NOW_ts4 <- auto.arima(NOW_ts, xreg=fourier(NOW_ts, K=4), seasonal=FALSE)
fit_NOW_ts5 <- auto.arima(NOW_ts, xreg=fourier(NOW_ts, K=5), seasonal=FALSE)
fit_NOW_ts6 <- auto.arima(NOW_ts, xreg=fourier(NOW_ts, K=6), seasonal=FALSE)
fit_NOW_ts7 <- auto.arima(NOW_ts, xreg=fourier(NOW_ts, K=7), seasonal=FALSE)
fit_NOW_ts8 <- auto.arima(NOW_ts, xreg=fourier(NOW_ts, K=8), seasonal=FALSE)
fit_NOW_ts9 <- auto.arima(NOW_ts, xreg=fourier(NOW_ts, K=9), seasonal=FALSE)
fit_NOW_ts10 <- auto.arima(NOW_ts, xreg=fourier(NOW_ts, K=10), seasonal=FALSE)
fit_NOW_ts11 <- auto.arima(NOW_ts, xreg=fourier(NOW_ts, K=11), seasonal=FALSE)
fit_NOW_ts12 <- auto.arima(NOW_ts, xreg=fourier(NOW_ts, K=12), seasonal=FALSE)
```

```{r}
aics<-c(AIC(fit_NOW_ts1),AIC(fit_NOW_ts2),AIC(fit_NOW_ts3),AIC(fit_NOW_ts4),AIC(fit_NOW_ts5),AIC(fit_NOW_ts6),AIC(fit_NOW_ts7),AIC(fit_NOW_ts8),AIC(fit_NOW_ts9),AIC(fit_NOW_ts10),AIC(fit_NOW_ts11),AIC(fit_NOW_ts12))
plot(aics)
```

```{r}
fc_NOW_ts1 <- forecast(fit_NOW_ts1, xreg=fourier(NOW_ts, K=1, h=26))
plot(fc_NOW_ts1)
```

```{r}
fc_NOW_ts1
```

```{r}
accuracy(fc_NOW_ts1)
```

```{r}
accuracy(fc_arima_NOW_ts)
```

```{r}
accuracy(fc_NOW_ts1)
```

#### Graph for ORE

```{r}
ORE <- read_csv("/cloud/project/CSV/ORE.csv", col_types = cols(Week = col_date(format = "%Y-%m-%d")))
ORE_ts <- ts(ORE[,2], freq=365.25/7, start=2015+247/365.25)
ORE_ts %>%
  autoplot()
```

```{r}
td_decomp <- decompose(na.locf(ORE_ts), type="additive")
autoplot(td_decomp)
```

```{r}
training_ORE <- subset(ORE_ts, end=length(ORE_ts)-8)
test_ORE <- subset(ORE_ts, start=length(ORE_ts)-8)
fc_training_ORE<-forecast(training_ORE)
fc_training_ORE %>%
  forecast(h=10) %>%
  autoplot() +autolayer(test_ORE)
```

```{r}
fc_training_ORE
```

```{r}
fc_ORE<-forecast(ORE_ts)
fc_ORE %>%
  forecast(h=50) %>%
  autoplot()
```

```{r}
tail(ORE_ts)
min(ORE_ts)
max(ORE_ts)
which.min(ORE_ts)
```

```{r}
bestfit_ORE_ts <- list(aicc=Inf)
for(i in 1:25)
{
  fit_ORE_ts <- auto.arima(ORE_ts, xreg=fourier(ORE_ts, K=i), seasonal=FALSE)
  if(fit_ORE_ts$aicc < bestfit_ORE_ts$aicc)
    bestfit_ORE_ts <- fit_ORE_ts
  else break;
}
```

```{r}
summary(bestfit_ORE_ts)
```

```{r}
fc_arima_ORE_ts <- forecast(bestfit_ORE_ts, xreg=fourier(ORE_ts, K=1, h=26))
plot(fc_arima_ORE_ts)
```

```{r}
fc_arima_ORE_ts
```

```{r}
fit_ORE_ts1 <- auto.arima(ORE_ts, xreg=fourier(ORE_ts, K=1), seasonal=FALSE)
fit_ORE_ts2 <- auto.arima(ORE_ts, xreg=fourier(ORE_ts, K=2), seasonal=FALSE)
fit_ORE_ts3 <- auto.arima(ORE_ts, xreg=fourier(ORE_ts, K=3), seasonal=FALSE)
fit_ORE_ts4 <- auto.arima(ORE_ts, xreg=fourier(ORE_ts, K=4), seasonal=FALSE)
fit_ORE_ts5 <- auto.arima(ORE_ts, xreg=fourier(ORE_ts, K=5), seasonal=FALSE)
fit_ORE_ts6 <- auto.arima(ORE_ts, xreg=fourier(ORE_ts, K=6), seasonal=FALSE)
fit_ORE_ts7 <- auto.arima(ORE_ts, xreg=fourier(ORE_ts, K=7), seasonal=FALSE)
fit_ORE_ts8 <- auto.arima(ORE_ts, xreg=fourier(ORE_ts, K=8), seasonal=FALSE)
fit_ORE_ts9 <- auto.arima(ORE_ts, xreg=fourier(ORE_ts, K=9), seasonal=FALSE)
fit_ORE_ts10 <- auto.arima(ORE_ts, xreg=fourier(ORE_ts, K=10), seasonal=FALSE)
fit_ORE_ts11 <- auto.arima(ORE_ts, xreg=fourier(ORE_ts, K=11), seasonal=FALSE)
fit_ORE_ts12 <- auto.arima(ORE_ts, xreg=fourier(ORE_ts, K=12), seasonal=FALSE)
```

```{r}
aics<-c(AIC(fit_ORE_ts1),AIC(fit_ORE_ts2),AIC(fit_ORE_ts3),AIC(fit_ORE_ts4),AIC(fit_ORE_ts5),AIC(fit_ORE_ts6),AIC(fit_ORE_ts7),AIC(fit_ORE_ts8),AIC(fit_ORE_ts9),AIC(fit_ORE_ts10),AIC(fit_ORE_ts11),AIC(fit_ORE_ts12))
plot(aics)
```

```{r}
fc_ORE_ts1 <- forecast(fit_ORE_ts1, xreg=fourier(ORE_ts, K=1, h=26))
plot(fc_ORE_ts1)
```

```{r}
fc_ORE_ts1
```

```{r}
accuracy(fc_ORE_ts1)
```

```{r}
accuracy(fc_arima_ORE_ts)
```

```{r}
accuracy(fc_ORE_ts1)
```
